[package]
name = "dirmerge"
version = "0.1.0"
edition = "2021"
description = "Directory merging library"
readme = "README.md"
license = "MIT"
keywords = ["filesystem", "recursive", "copy"]
categories = ["filesystem"]
include = ["**/*.rs", "Cargo.toml", "LICENSE", "README.md"]

[dependencies]
